"""admin user

Revision ID: f793e5b7ebc9
Revises: e1b1d1c9fc61
Create Date: 2025-08-03 13:07:59.368598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f793e5b7ebc9'
down_revision: Union[str, Sequence[str], None] = 'e1b1d1c9fc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Boolean
    import bcrypt

    user_table = table('user',
                       column('username', String),
                       column('hashed_password', String),
                       column('is_owner', Boolean),
                       )
    op.bulk_insert(user_table, [
        {
            'username': 'massimo',
            'hashed_password': "$2b$12$JDeKJiV1PFcl1vlxU71zJ.N0LmyFMFjpGErIiJPDYaYCDwyROLJTO",
            'is_owner': True,
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
